import { describe, it, expect } from 'vitest'
import { keyPaths, keyEntries, hydrateLocale, PATH_SEP } from '../hydrate'
import en from '../en.json'
// Generated by scripts/build-locale-values.mjs via the Vitest globalSetup
// (dev/i18n-global-setup.js) -- see the import comment in locale-parity.test.js
// for why parity itself is checked against source/ instead.
import esValues from '../es.json'
import frValues from '../fr.json'
import huValues from '../hu.json'
import esSource from '../source/es.json'
import frSource from '../source/fr.json'
import huSource from '../source/hu.json'

const S = PATH_SEP

describe('keyPaths', () => {
  it('walks nested objects depth-first in insertion order', () => {
    expect(keyPaths({ b: { y: 1, x: 2 }, a: 3 })).toEqual([`b${S}y`, `b${S}x`, 'a'])
  })
})

describe('keyEntries', () => {
  it('pairs each leaf path with its value in the same traversal', () => {
    expect(keyEntries({ b: { y: 1, x: 2 }, a: 3 })).toEqual([
      [`b${S}y`, 1],
      [`b${S}x`, 2],
      ['a', 3],
    ])
  })
})

describe('hydrateLocale', () => {
  it('rebuilds a nested dictionary from a flat values array', () => {
    const shape = { greeting: 'hi', nested: { a: 1, b: 2 } }
    const values = ['bonjour', 10, 20]
    expect(hydrateLocale(shape, values)).toEqual({ greeting: 'bonjour', nested: { a: 10, b: 20 } })
  })

  it('round-trips a key containing a literal dot without mis-nesting', () => {
    // A dot is svelte-i18n's own nesting delimiter, so such a key is unusual,
    // but the position encoding must not silently split it into extra levels.
    const shape = { 'version.1.5': 'x', nested: { 'a.b': 'y' } }
    const values = keyEntries(shape).map(([, v]) => v)
    expect(hydrateLocale(shape, values)).toEqual(shape)
  })
})

describe('locale build round trip', () => {
  // This is the guard for the actual size-saving change: es/fr/hu ship as
  // position-encoded arrays (build-locale-values.mjs) and get reassembled
  // into a real dictionary at load time (index.js). If either side's key
  // traversal order drifts, values silently land under the wrong key -- this
  // catches that by reconstructing the full dictionary and diffing it
  // against the human-maintained source, not just checking array lengths.
  for (const [name, values, source] of [
    ['es', esValues, esSource],
    ['fr', frValues, frSource],
    ['hu', huValues, huSource],
  ]) {
    it(`${name}.json rehydrates to exactly source/${name}.json`, () => {
      expect(hydrateLocale(en, values)).toEqual(source)
    })
  }
})
